---
# The playbook for common tasks

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: true

- name: Create the hosts file for all machines
  template: src=etc/hosts.j2 dest=/etc/hosts
  sudo: true

- hostname: name={{host}}
  sudo: true