---
# The plays for mesos masters

- name: Install dependencies
  apt: name=$item state=installed
  with_items:
    - default-jre
    - python-setuptools
    - python-protobuf
    - libcurl3
  sudo: true

- name: Fetch mesos
  get_url: url=http://downloads.mesosphere.io/master/ubuntu/13.04/mesos_0.16.0_amd64.deb dest=/vagrant/mesos.deb

- name: Install mesos
  command: dpkg -i /vagrant/mesos.deb creates=/usr/local/bin/mesos
  sudo: true

- name: Fetch install scripts
  get_url: url=http://downloads.mesosphere.io/master/ubuntu/12.04/mesos_0.16.0_amd64.egg dest=/vagrant/mesos.egg

- name: Easy_install mesos
  command: easy_install /vagrant/mesos.egg creates=/usr/local/lib/python2.7/dist-packages/mesos.egg
  sudo: true
  notify: restart mesos

- name: Copy the config for mesos
  template: src=zk.j2 dest=/etc/mesos/zk
  sudo: true
  notify: restart mesos
